version: "3.8"
services:
  db:
    image: postgres:15
    container_name: rust_chat_db
    restart: always
    ports:
      - "15432:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "max_prepared_transactions=100"

networks:
  backend:
    driver: bridge

volumes:
  db_data:
