### signup user
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "test",
    "username": "Alice Chen",
    "email": "alice@acme.org",
    "password": "123456"
}

### signup user2
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "workspace": "test",
    "username": "Bob Chen",
    "email": "bob@acme.org",
    "password": "123456"
}

### signin user (valid)
# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "alice@acme.org",
    "password": "123456"
}

### store token from signin response
@token = {{signin.response.body.token}}

### get chat list
GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}

### get user list
GET http://localhost:6688/api/users
Authorization: Bearer {{token}}

### create chat
POST http://localhost:6688/api/chats
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Family Chat",
    "members": [1, 3],
    "public": false
}
### upload files
POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="xdiff1.png"
Content-Type: application/octet-stream

< rust_chat/asset/notify_server.png
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--

### get files
GET http://localhost:6688/api/files/1/0e1/907/702a2d2fe4dc56a8e682316556d5ff09b9.png
Authorization: Bearer {{token}}

### send a message
POST http://localhost:6688/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Hello, World!",
    "files": []
}

### get messages
GET http://localhost:6688/api/chats/1/messages
Authorization: Bearer {{token}}
